#! /bin/bash
read -ep "Introduce la URL del vídeo: " url
echo -n "Introduce el video de salida (/mnt/e/Vídeos/): "
read -e -i "/mnt/e/Vídeos/" v_salida
ffmpeg -i "$(youtube-dl -g "${url}")" -c copy "${v_salida}"