#! /bin/bash
#v288p_nologo
#################################################################################################
#set -x
echo -n "Introduce el video de entrada: (/mnt/e/Vídeos/) "
read -e -i "/mnt/e/Vídeos/" v_entrada			# RUTA COMPLETA DEL VÍDEO DE ENTRADA
ruta="${v_entrada%/*}/"
nom_f="${v_entrada##*/}"
ext_f=".${nom_f##*.}"
nom_f="${nom_f%.*}"

fontfile="/mnt/c/Windows/Fonts/impact.ttf" # Ruta de la fuente de texto

read -ep "Introduce el inicio de la secuencia (00:00:00.000): " -i "00:00:00.000" t_ini # Inicio de la secuencia
v_dur=$(ffprobe -v error -show_entries format=duration -sexagesimal -of default=noprint_wrappers=1:nokey=1 "${v_entrada}")
read -ep "Introduce el final de la secuencia (${v_dur}): " -i "${v_dur}" t_fin # Fin de la secuencia
secuencia_t1="$(date --date ${t_ini} +%s.%N)"
secuencia_t2="$(date --date ${v_dur} +%s.%N)"
setpts=$(echo "scale=6;140/(${secuencia_t2}-${secuencia_t1})" | bc )
atempo=$(echo "scale=6; 1/${setpts}" | bc )
#echo ${atempo}
read -p "Introduce el titular 1: " txt_l1				# LINEA 1 DE TEXTO A INCRUSTAR
read -p "Introduce el titular 2: " txt_l2		# LINEA 2 DE TEXTO A INCRUSTAR

v_salida="${ruta}${nom_f}_140s.mp4"	# RUTA COMPLETA DEL VIDEO DE SALIDA

f_txt_l1="
	[0:v]
  drawtext=
		fontfile='${fontfile}':
		text='${txt_l1}':
		fontcolor=white:
		borderw=1:
		fontsize=18:
		alpha=0.67:
		x=(w-tw)/2:
		y=(th/4)
"
f_txt_l2="
,
  drawtext=
		fontfile='${fontfile}':
		text='${txt_l2}':
		fontcolor=white:
		borderw=1:
		fontsize=18:
		alpha=0.67:
		x=(w-tw)/2:
		y=(4*th/2)
"
f_setpts="
,
 	setpts='${setpts}*PTS'
[v]
;
[0:a]
	atempo='${atempo}'
[a]
"
filter_complex="${f_txt_l1}${f_txt_l2}${f_setpts}"

##########
# FFMPEG #
##########

ffmpeg -y \
	-ss "${t_ini}" \
	-to "${t_fin}" \
	-i "${v_entrada}" \
	-filter_complex "${filter_complex}" \
	-map '[v]' \
	-map '[a]' \
	-c:a aac \
	-q:a 1 \
	-ac 1 \
	-c:v h264 \
	-crf 30 \
	"${v_salida}"