#! /bin/bash
#v288p_nologo
#################################################################################################

echo -n "Introduce el video de entrada: "
read -e v_entrada			# RUTA COMPLETA DEL AUDIO DE ENTRADA
ruta="${v_entrada%/*}/"
nom_f="${v_entrada##*/}"
ext_f=".${nom_f##*.}"
nom_f="${nom_f%.*}"

fontfile="/mnt/c/Windows/Fonts/impact.ttf" # Ruta de la fuente de texto

read -ep "Introduce el inicio de la secuencia (00:00:00.000): " -i "00:00:00.000" t_ini # Inicio de la secuencia
v_dur=$(ffprobe -v error -show_entries format=duration -sexagesimal -of default=noprint_wrappers=1:nokey=1 "${v_entrada}")
read -ep "Introduce el final de la secuencia (${v_dur}): " -i "${v_dur}" t_fin # Fin de la secuencia
read -p "Introduce el titular 1: " txt_l1				# LINEA 1 DE TEXTO A INCRUSTAR
read -p "Introduce el titular 2: " txt_l2		# LINEA 2 DE TEXTO A INCRUSTAR

v_salida="${ruta}${nom_f}_h264_288p_crf30_aac_q1_ac1_nologo.mp4"	# RUTA COMPLETA DEL VIDEO DE SALIDA

f_resolucion="
	[0:v]
		scale=
			width=-2:
			height=288:
			flags=bicubic
	"
f_txt_l1="
,
  drawtext=
		fontfile='${fontfile}':
		text='${txt_l1}':
		fontcolor=white:
		borderw=1:
		fontsize=18:
		alpha=0.67:
		x=(w-tw)/2:
		y=(th/4)
"
f_txt_l2="
,
  drawtext=
		fontfile='${fontfile}':
		text='${txt_l2}':
		fontcolor=white:
		borderw=1:
		fontsize=18:
		alpha=0.67:
		x=(w-tw)/2:
		y=(4*th/2)
	[v]
"
filter_complex="${f_resolucion}${f_txt_l1}${f_txt_l2}"

##########
# FFMPEG #
##########

ffmpeg -y \
	-ss "${t_ini}" \
	-to "${t_fin}" \
	-i "${v_entrada}" \
	-filter_complex "${filter_complex}" \
	-map '[v]' \
	-map '0:a' \
	-c:a aac \
	-q:a 1 \
	-ac 1 \
	-c:v h264 \
	-crf 30 \
	"${v_salida}"