#! /bin/bash
# CONVIERTE UN VIDEO EN GIF ANIMADO
echo -n "Introduce el video de entrada: "
read -e -i "/mnt/d/Vídeos/" v_entrada			# RUTA COMPLETA DEL FICHERO DE VIDEO DE ENTRADA
ruta="${v_entrada%/*}/" # RUTA DEL FICHERO DE VIDEO DE ENTRADA SIN EL NOMBRE NI LA EXTENSIÓN
nom_f="${v_entrada##*/}" # NOMBRE DEL FICHERO DE VIDEO DE ENTRADA CON EXTENSIÓN
ext_f=".${nom_f##*.}" # EXTENSIÓN DEL FICHERO DE VIDEO DE ENTRADA
nom_f="${nom_f%.*}" # NOMBRE DEL FICHERO DE VIDEO DE ENTRADA SIN EXTENSIÓN
paleta="${ruta}${nom_f}.png" # NOMBRE DEL FICHERO DE LA PALETA DE 256 COLORES DEL GIF ANIMADO PARA OBTENER PRECISIÓN DE COLOR
echo -n "Introduce el número de fotogramas por segundo (10): "
read -e -i "10" fps			# RUTA COMPLETA DEL FICHERO DE VIDEO DE ENTRADA
#fps="0.5" # NÚMERO DE FOTOGRAMAS QUE SE VAN A CAPTURAR DEL VIDEO CADA SEGUNDO 
echo -n "Introduce en que proporción se modifica el retraso entre fotogramas (0.1 multiplica x10 la velocidad): "
read -e -i "0.1" pts			# RUTA COMPLETA DEL FICHERO DE VIDEO DE ENTRADA

v_salida="${ruta}${nom_f}_v2gif.gif" # NOMBRE DEL FICHERO GIF ANIMADO INCLUIDA RUTA Y EXTENSIÓN

# CREACIÓN DE LA PALETA DE 256 COLORES ADAPTADA AL VIDEO
echo ffmpeg -y -i "${v_entrada}" -filter_complex "[0:v]fps=${fps},split[a][b];[b]palettegen[p];[a][p]paletteuse,setpts=$pts*PTS[v]" -map '[v]' "${v_salida}"

ffmpeg \
	-y \
	-i "${v_entrada}" \
  	-filter_complex \
    	"
		[0:v]fps=${fps},
		split[a][b];
		[b]palettegen[p];
		[a][p]paletteuse,
		setpts=$pts*PTS[v]
		" \
	-map '[v]' \
	"${v_salida}"