#! /bin/bash
# CONVIERTE UN VIDEO EN GIF ANIMADO
echo -n "Introduce el video de entrada: "
read -e -i "/mnt/d/Vídeos/" v_entrada			# RUTA COMPLETA DEL FICHERO DE VIDEO DE ENTRADA
ruta="${v_entrada%/*}/" # RUTA DEL FICHERO DE VIDEO DE ENTRADA SIN EL NOMBRE NI LA EXTENSIÓN
nom_f="${v_entrada##*/}" # NOMBRE DEL FICHERO DE VIDEO DE ENTRADA CON EXTENSIÓN
ext_f=".${nom_f##*.}" # EXTENSIÓN DEL FICHERO DE VIDEO DE ENTRADA
nom_f="${nom_f%.*}" # NOMBRE DEL FICHERO DE VIDEO DE ENTRADA SIN EXTENSIÓN
paleta="${ruta}${nom_f}.png" # NOMBRE DEL FICHERO DE LA PALETA DE 256 COLORES DEL GIF ANIMADO PARA OBTENER PRECISIÓN DE COLOR
echo -n "Introduce el número de fotogramas por segundo (0.5): "
read -e -i "0.5" fps			# RUTA COMPLETA DEL FICHERO DE VIDEO DE ENTRADA
#fps="0.5" # NÚMERO DE FOTOGRAMAS QUE SE VAN A CAPTURAR DEL VIDEO CADA SEGUNDO 

v_salida="${ruta}${nom_f}_v2gif.gif" # NOMBRE DEL FICHERO GIF ANIMADO INCLUIDA RUTA Y EXTENSIÓN

# CREACIÓN DE LA PALETA DE 256 COLORES ADAPTADA AL VIDEO
# echo "ffmpeg -y -i ${v_entrada} -vf fps=${fps},palettegen ${paleta}"
ffmpeg \
  -y \
  -i "${v_entrada}" \
  	-filter_complex \
    	fps="${fps}",palettegen=stats_mode=diff "${paleta}"

# CODIFICACIÓN DEL GIF EMPLEANDO LA PALETA DE COLORES DEL VIDEO
ffmpeg \
	-y \
	-r 5 \
	-i "${v_entrada}" \
	-i "${paleta}" \
	-filter_complex \
		"
        [0:v]fps="${fps}"[v1],
        [v1][1]paletteuse[v]
		" \
    -map '[v]' \
	"${v_salida}"

# ELIMINACIÓN DE LA PALETA
rm "${paleta}"