#! /bin/bash
# 01 Se discretiza ${filter_complex}
# 02 Se elimina el logotipo y se substituye por el texto @tocamgar
#    Se fija el tamaño en 360p
#    Se modifica el texto para que no expanda los caracteres especiales (: \)
#################################################################################################
#set -x
echo -n "Introduce el audio de entrada: "
read -e a_entrada			# RUTA COMPLETA DEL AUDIO DE ENTRADA
# a_entrada="/mnt/e/Sonido/PRENSA/EL DIARIO.ES/El exnúmero dos de Interior depositó ante.m4a"			# RUTA COMPLETA DEL AUDIO DE ENTRADA
ruta="${a_entrada%/*}/"		# SOLO LA RUTA DEL FICHERO DE AUDIO
nom_f="${a_entrada##*/}"	# NOMBRE DEL FICHERO CON EXTENSIÓN
ext_f=".${nom_f##*.}"		# EXTENSIÓN DEL FICHERO CON . DELANTE
nom_f="${nom_f%.*}"			# NOMBRE DEL FICHERO SIN EXTENSIÓN

echo -n "Introduce la ruta del vídeo de salida: "
read -e ruta_salida	# RUTA DEL VIDEO DE SALIDA

fontfile="/mnt/c/Windows/Fonts/impact.ttf"	# UBICACIÓN DE LA FUENTE DE TEXTO A EMPLEAR

read -p "Introduce el titular 1: " txt_l1				# LINEA 1 DE TEXTO A INCRUSTAR

read -p "Introduce el titular 2: " txt_l2		# LINEA 2 DE TEXTO A INCRUSTAR

read -p "Introduce la url: " url				# LINEA 2 DE TEXTO A INCRUSTAR

fondo="/mnt/e/Pictures/${nom_f}.png"
#logo="/mnt/e/Pictures/logo-cam_53x26.png"	# RUTA COMPLETA DE LA MARCA DE AGUA A INCRUSTAR

f_resolucion='
	[0:v]
		scale=
			width=-2:
			height=360:
			flags=bicubic
'
f_txt_l1='
,
  drawtext=
		fontfile='${fontfile}':
		text='${txt_l1}':
		fontcolor=white:
		borderw=1:
		fontsize=18:
		alpha=1.00:
		x=(w-tw)/2:
		y=(th/4):
		expansion=none
'
f_txt_l2='
,
  drawtext=
		fontfile='${fontfile}':
		text='${txt_l2}':
		fontcolor=white:
		borderw=1:
		fontsize=18:
		alpha=1.00:
		x=(w-tw)/2:
		y=(2*th/4)+text_h:
		expansion=none
'
f_url='
,
	drawtext=
		fontfile='${fontfile}':
		text='${url}':
		fontcolor=lightskyblue:
		borderw=1:
		fontsize=10:
		alpha=1.00:
		x=(w-tw)/2:
		y=(5*th):
		expansion=none
'
f_txt_logo='
,
  drawtext=
		fontfile='/mnt/c/Windows/Fonts/arial.ttf':
		text='@tocamgar':
		fontcolor=white:
		borderw=1:
		fontsize=18:
		alpha=0.60:
		x=w-tw-10:
		y=h-th-10:
		expansion=none
	[fondo]
'
f_showwaves="
;
[1:a]
	showwaves=
		s=300x100:
		mode=cline:
		colors=0xffffff,
	colorkey=
		color=0x000000:
		similarity=0.01:
		blend=0.1,
	format=argb,
	colorchannelmixer=
		aa=0.50
[waves]
;
[fondo][waves]
	overlay=
		x=(main_w-overlay_w)/2:
		y=(main_h-overlay_h-5)
[v]
"

filter_complex="${f_resolucion}${f_txt_l1}${f_txt_l2}${f_url}${f_txt_logo}${f_showwaves}"

v_salida="${ruta_salida}${nom_f}_waves_h264_288p_crf30_aac_q1_ac1_01.mp4"	# RUTA COMPLETA DEL VIDEO DE SALIDA

##########
# FFMPEG #
##########

ffmpeg -y \
  -i "${fondo}"\
  -i "${a_entrada}"\
 	-filter_complex "${filter_complex}" \
  -map '[v]' \
  -map '1:a' \
	-c:a aac \
	-q:a 1 \
	-ac 1 \
	-c:v h264 \
	-crf 30 \
  "${v_salida}"